name: Configuration Issue
description: Report a configuration issue in the project
title: "[CONFIG] "
labels: ["configuration"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this configuration issue report!

  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the configuration issue is.
      placeholder: "Describe the configuration issue"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: "List the steps to reproduce the configuration issue"
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Describe the expected behavior"
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: "Describe the actual behavior"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "Add screenshots here"

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: e.g. Windows 10, macOS 11.2
        - Python Version: e.g. 3.8.5
      placeholder: "Describe your environment"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information about the problem here.
      placeholder: "Add additional information here"
