FROM {_from}

# Avoid stuck at console asking for input
ARG DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    && apt-get clean

# Set the working directory
WORKDIR {_workdir}

# Set the default command
CMD ["/bin/bash"]
